### ISSUE TITLE
allowed_types are not considered

### ISSUE THREAD

**Issue by agitator** [plone/archetypes.referencebrowserwidget#16]
if allowed_types are defined, only selectable items should be displayed!

```
self.request.form['portal_type'] = []
```
imho ^ removes the portal_type query parameter and disables allowed_types

removing that line solves the problem in "real life" but it seems this feature is not taken into account within the tests 

```
Failure in test test_popup_items (archetypes.referencebrowserwidget.tests.test_product.IntegrationTestCase)
Traceback (most recent call last):
  File "/Users/peter/workspace/python/parts/opt/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/Users/peter/workspace/buildout.coredev/src/archetypes.referencebrowserwidget/src/archetypes/referencebrowserwidget/tests/test_product.py", line 665, in test_popup_items
    self.assertEqual(len(ROWS.findall(body)), wanted_rows)
  File "/Users/peter/workspace/python/parts/opt/lib/python2.7/unittest/case.py", line 509, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/peter/workspace/python/parts/opt/lib/python2.7/unittest/case.py", line 502, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 3 != 7
```

https://github.com/plone/archetypes.referencebrowserwidget/commit/48af4e89cadf0b23357adacd0f212385615eb926?diff=unified

**Comment by frisi** [comment]
the widget displays items that are not in allowed_types to be able navigate using the breadcrumbs and result-items.
see [this comment](https://github.com/plone/archetypes.referencebrowserwidget/commit/a537138d8fbfdbacd571886dd3728debe45ea9ee#commitcomment-9874536) for details.

**Comment by frisi** [comment]
@agitator this should fix your usecase too - could you please confirm that?

**Comment by agitator** [comment]
allowed_types works for me, does your change take the browsable_types in account?

**Comment by frisi** [comment]
yes, it's only showing items with `view.isBrowable(item)==True` (see https://github.com/plone/archetypes.referencebrowserwidget/blob/issue16-allowed_types/src/archetypes/referencebrowserwidget/browser/popup.pt#L184)

**Comment by agitator** [comment]
correction about the allowed_types: if you have many items in a folder, the batch is calculated over all items, having only a condition in the templates ends up in empty pages in the batch.

**Comment by frisi** [comment]
good point @agitator - i updated my PR (https://github.com/plone/archetypes.referencebrowserwidget/commit/084d6e4df10050804efa7a388519acb48c0c65a1) - should work fine now.

please test and report

for performance reasons i add the information (browseable and referable) to the batch-items instead of re-computing them again in the result list.

**Comment by agitator** [comment]
looks good to me now
