### ISSUE TITLE
Missing semicolon in template

### ISSUE THREAD

**Issue by uschwarz** [plone/archetypes.referencebrowserwidget#18]
In referencebrowser.pt:

```
<tal:block condition="python: (can_view or not hide_inaccessible)"
define="obj python:refs[0];
obj_path python: '/'.join(obj.getPhysicalPath());
obj_interface_info nocall:obj/@@plone_interface_info
can_view python: helper.canView(obj)">
```

fails with 

> Not a valid path-expression. - String: "nocall:obj/@@plone_interface_info can_view python: helper.canView(obj)"

**Comment by jterstriep** [comment]
Can we get a new version, 2.5.3 with this fix on pypi?

**Comment by frisi** [comment]
before doing a release, please also review and merge the other pull requests.

#20 looks good, to me and is very much needed for the release too, i'll merge it right away
#17 test do pass with this change, i asked @mitakas for a changelog
for #21 i'd like to get some feedback
