### ISSUE TITLE
Wild card search for ZCTextIndexes?

### ISSUE THREAD

**Issue by gbastien** [plone/archetypes.referencebrowserwidget#23]
Hi,

I think searching using a ZCTextIndex (like default SearchableText is) should be searched as wildcard (so "word", should be searched like "word*").  This make more sense to any users, we systematically overrides the search view to do this...

I would like to propose a Pull request where a widget.wild_card_search parameter could ne set to True if we want the widget to behave like that.  I would even remove this as a parameter but add a checkbox in the popup that would show when a ZCTextIndex index is searched.

What about this?

Thank you!

Gauthier

**Comment by gbastien** [comment]
I even see this branch that was already about that...

https://github.com/plone/archetypes.referencebrowserwidget/tree/livesearch

**Comment by gbastien** [comment]
@keul @frisi 

what do you think of that?  Moreover, could we have a new release @esteele including the fix that does the sorting works?

Thank you ;-)

Gauthier

**Comment by keul** [comment]
It seems a good change IMHO  and I personally think you can skip the "wild_card_search" flag (or: add it but default it to the new behavior).

But I don't know who can take this kind of decision here. :smiley:

**Comment by gbastien** [comment]
@keul 

I will propose à PR soon, we will see ;-)

Thank you!

Gauthier

**Comment by frisi** [comment]
personally, i'd agree, that it's okay to automatically append a `*` to the querystring when it's not present.

to be 100% backward compatible we'd need a `use_wildcard_search` parameter which defaults to `False`
on the other hand, this would mean very view people will take advantage of this feature.

integrators might use other indexes (textindexng for example) that allow advanced search queries like searching for `*dog NOT "pet food"`
so there should definitely be a way to switch off this feature for this case.

keep in mind, that skilled editors already use * if the want to perform a wildcard search.
how can/would we still support to search for an exact phrase/word. so people can search for "dog" without finding "dogfood". maybe do not append `*` when query is wrapped with `""`.

**Comment by gbastien** [comment]
@frisi, good idea, I was about to add some check box like "exact match", but adding a small help message specifying that the search is done fulltext and that wrapping it with "" would query exact match is pretty easy to set up.

I will add a use_wildcard_search parameter set to True by default that will add a "*" in relevant cases and add an help message for exact match.

I will propose this PR next week.

Thank you,

Gauthier

**Comment by gbastien** [comment]
This was merged, thank you @vincentfretin !

**Comment by vincentfretin** [comment]
The new messages are in plone.app.locales now.

**Comment by gbastien** [comment]
OK, thank you @vincentfretin I will propose french translations...

+++

Gauthier
